### ISSUE TITLE
Cannot read some rpm files: short read error

### ISSUE THREAD

**Issue by vacuumn** [sassoftware/go-rpmutils#1]
I am trying to open `openoffice.org-core-3.1.1-19.10.el5_8.4.i386.rpm` file using PayloadReader. 
Some of the entries are processed and then BOOM:
`short read, got 18, expected 67`
after which reading is stopped due to incorrect offset

I still can open this rpm via `rpm2cpio.sh filename.rpm  |  cpio -idmv`

Link to file https://dl.dropboxusercontent.com/u/857905/openoffice.org-core-3.1.1-19.10.el5_8.4.i386.rpm

**Comment by mtharp** [comment]
Looks like this got fixed back in 2017, so a very late thank-you for the report.
