### ISSUE TITLE
unsupported datatype for string: 4, tag: 1003

### ISSUE THREAD

**Issue by volker-raschek** [sassoftware/go-rpmutils#11]
Hello, everyone, 
I use your library to read rpm metadata. But I get an error with some RPMs that I can't do anything with. 

```
unsupported datatype for string: 4, tag: 1003
```

It is thrown into line [194](https://github.com/sassoftware/go-rpmutils/blob/a8f1baeba37b09447202f9b734cb1bdf971ecd8b/header.go#L194) of the header.go file. 

I hope you can help me to find out if something is wrong with the source code or the RPM. An RPM, which caused the error is attached.

Many greetings and stay healthy

[icons-test-0-0.1.1-0.nonarch.rpm.tar.gz](https://github.com/sassoftware/go-rpmutils/files/4491890/icons-test-0-0.1.1-0.nonarch.rpm.tar.gz)

**Comment by Richterrettich** [comment]
tag 1003 is the epoch tag, which is defined to be an integer not a string:
https://github.com/rpm-software-management/rpm/blob/master/lib/rpmtag.h#L77
so this basically traces down to 
https://github.com/sassoftware/go-rpmutils/blob/a8f1baeba37b09447202f9b734cb1bdf971ecd8b/header.go#L337

**Comment by pixdrift** [comment]
I am interested to know what generated this RPM?

The output using the native RPM command suggests there are more than just the epoch issue with the package.

```
$ rpm -qip icons-test-0-0.1.1-0.nonarch.rpm
Name        : icons-test
Epoch       : 0
Version     : 0.1.1
Release     : 0
Architecture: nonarch
Install Date: (not installed)
Group       : Unspecified
Size        : 14
License     : MIT
Signature   : (none)
Source RPM  : (none)
Build Date  : (none)
Build Host  : (none)
Relocations : (not relocatable)
Summary     :
Description :
```

**Comment by volker-raschek** [comment]
I have created the rpm with the [rpm-builder](
https://github.com/Richterrettich/rpm-builder).

**Comment by mtharp** [comment]
This should be fixed now. Thanks for the report!
