### ISSUE TITLE
GetStrings(PROVIDEFLAGS) fails (CentOS + Raspberry)

### ISSUE THREAD

**Issue by stephan57160** [sassoftware/go-rpmutils#12]
GetStrings(PROVIDEFLAGS), fails for all official CentOS packages I could try from there:
   http://mirror.centos.org/altarch/7/updates/armhfp/Packages/

Sample code below:
```
        ...
	flg, err := rpm.Header.GetStrings(rpmutils.PROVIDEFLAGS)
	if err == nil {
		for _, f := range flg {
			fmt.Printf("- flg    : %#v\n", f)
		}
	} else {
		fmt.Printf("GetStrings(PROVIDEFLAGS) error: %s\n", err)
	}
```

Result is always "unsupported datatype for string: 4, tag: 1112"

**Comment by mtharp** [comment]
PROVIDEFLAGS is an integer array: https://github.com/rpm-software-management/rpm/blob/master/lib/rpmtag.h#L186

GetStrings only works for string and string-array types. For integers you should use GetInts, or the generic Get.
