### ISSUE TITLE
Issues dealing with some empty RPMs

### ISSUE THREAD

**Issue by vikmik** [sassoftware/go-rpmutils#20]
Hello,

I stumbled upon a case where `PayloadReaderExtended`  returns an error on some empty RPMs, like https://fedora.mirror.constant.com/fedora/linux/updates/testing/32/Everything/x86_64/Packages/n/nagios-plugins-all-2.3.3-1.fc32.x86_64.rpm

The following code will fail:
```go
	f, _ := os.Open("/tmp/nagios-plugins-all-2.3.3-1.fc32.x86_64.rpm")
	rpm, _ := rpmutils.ReadRpm(f)
	payloadReader, err := rpm.PayloadReaderExtended()  /// <<<< fails
```

The error comes from this line: https://github.com/sassoftware/go-rpmutils/blob/e5cf0f808585c10c36b3c133f0a524b93afd34d1/header.go#L180 as there is no DIRNAMES entry in the rpm.

This is easy to workaround by checking the error, but is not ideal - so I'm opening this issue in case I'm doing something wrong. Or does this look like a bug in the library?

**Comment by mtharp** [comment]
Thank you for the report. This seems like a bug to me, so I fixed it.

**Comment by vikmik** [comment]
Oh awesome - thanks for the quick fix! :)
