### ISSUE TITLE
Error to extract single file from rpm with rpmutils.PayloadReader()

### ISSUE THREAD

**Issue by ZiqianXu** [sassoftware/go-rpmutils#30]
Thanks for developing this pure golang rpm utils lib, it's very easy to use!
Recently we encountered a random issue on extracted single file from rpm that the last 32 bytes are all null-byte.
The code to extract single file
```
rpmReader, err := os.Open(rpmFilepath)
rpmInfo, err := rpmutils.ReadRpm(rpmReader)
rpmPayloadReader, err := rpmInfo.PayloadReaderExtended()
fileInfo, err := rpmPayloadReader.Next()

buf := make([]byte, fileInfo.Size())
 _, err := payloadReader.Read(buf)
return os.WriteFile(extractFilepath, buf, os.FileMode(fileInfo.Mode()).Perm())
```
Does the code look right to you?

Note: it happened randomly on different files

Thanks for your help on this!

**Comment by mtharp** [comment]
Hi,

One thing about the Go interface contract for `Read` is that you cannot assume it will fill the buffer in one call. It may return only part, and need another call to get the rest. `io.ReadFull` will do this for you if you know the buffer is the right size:
```go
buf := make([]byte, fileInfo.Size())
_, err := io.ReadFull(payloadReader, buf)
```

Or you can take advantage of payloadReader returning EOF when it gets to the end of the current file:
```go
buf, err := io.ReadAll(payloadReader)
```

Please let me know if this addresses your issue.
