### ISSUE TITLE
Configurable logger?

### ISSUE THREAD

**Issue by joelanford** [sassoftware/go-rpmutils#4]
I'm using this library in another library I'm writing, and I noticed that it logs lots of debug messages while reading RPMs.  I'd prefer not to have these log messages show up intermingled when called by my library.

I don't mind submitting a PR, but just wanted to create an issue here first for discussion. Can those log statements be removed? Or can this library be updated to make debug logging be explicitly enabled?

~~Right now my workaround is to call `log.SetOutput(ioutil.Discard)`, but that disables ALL log output, not just the log output from this library.~~

EDIT: Just realized log.SetOutput doesn't solve my problem because the stdlib log package isn't doing the logging.  It looks like the following worked though:

```go
func init() {
	nullLogger := logging.NewLogBackend(ioutil.Discard, "", 0)
	logging.SetBackend(nullLogger)
}
```

Is there a better way to do this with `github.com/op/go-logging`?

**Comment by guo1017138** [comment]
I have the same issue and the workaround works for me. I also suggest author to expose API the log.go to external lib to make more convenient.

**Comment by mtharp** [comment]
The logging was not very useful so I removed it entirely.
